baseURL = "http://savetheshark.netlify.app/"
languageCode = 'en-us'
title = 'Save the Shark'
disableKinds = ["taxonomy"]
[permalinks]
  donate = "/donate/"
  discover = "/discover/"
  merch = "/merch/"
